# Generated by Django 3.2.6 on 2022-01-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0002_qweqwe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code_med_dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_id', models.IntegerField(blank=True, null=True)),
                ('rzn', models.CharField(blank=True, max_length=20, null=True)),
                ('parent', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('localization', models.CharField(blank=True, max_length=1000, null=True)),
                ('material', models.CharField(blank=True, max_length=1000, null=True)),
                ('metal', models.CharField(blank=True, max_length=1000, null=True)),
                ('sctid', models.CharField(blank=True, max_length=1000, null=True)),
                ('order', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='qweqwe',
        ),
    ]
