# Generated by Django 3.2.6 on 2022-02-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0006_alter_myuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_kc_group',
            name='code_usl_kz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
