# Generated by Django 3.2.6 on 2022-02-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0007_group_kc_group_code_usl_kz'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_kc_group',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
