# Generated by Django 3.2.6 on 2022-02-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0008_group_kc_group_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_kc_group',
            name='count',
        ),
    ]
