# Generated by Django 3.2.6 on 2022-02-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0009_remove_group_kc_group_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='t003',
            name='code_usl_kz',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
