# Generated by Django 3.2.6 on 2022-02-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0010_t003_code_usl_kz'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatePers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
