# Generated by Django 3.2.6 on 2022-02-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0011_updatepers'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatepers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='okb2.myuser'),
        ),
    ]
