# Generated by Django 3.2.6 on 2022-02-16 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('okb2', '0013_alter_updatepers_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatePersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=22, null=True)),
                ('coderem', models.CharField(blank=True, max_length=3, null=True)),
                ('rem', models.CharField(blank=True, max_length=255, null=True)),
                ('id_pac', models.CharField(blank=True, max_length=36, null=True)),
                ('fam_reestr', models.CharField(blank=True, max_length=24, null=True)),
                ('im_reestr', models.CharField(blank=True, max_length=16, null=True)),
                ('ot_reestr', models.CharField(blank=True, max_length=26, null=True)),
                ('dr_reestr', models.DateField(blank=True, null=True)),
                ('w_reestr', models.IntegerField(blank=True, null=True)),
                ('nhistory_r', models.CharField(blank=True, max_length=50, null=True)),
                ('mr_reestr', models.CharField(blank=True, max_length=150, null=True)),
                ('data_usl', models.DateField(blank=True, null=True)),
                ('smo_reestr', models.IntegerField(blank=True, null=True)),
                ('vpolis_ree', models.IntegerField(blank=True, null=True)),
                ('npolis_ree', models.CharField(blank=True, max_length=18, null=True)),
                ('spolis_ree', models.CharField(blank=True, max_length=18, null=True)),
                ('smo_ok_ree', models.CharField(blank=True, max_length=5, null=True)),
                ('doctype_re', models.CharField(blank=True, max_length=20, null=True)),
                ('docser_ree', models.CharField(blank=True, max_length=19, null=True)),
                ('docnum_ree', models.CharField(blank=True, max_length=20, null=True)),
                ('snils_ree', models.CharField(blank=True, max_length=14, null=True)),
                ('fam', models.CharField(blank=True, max_length=24, null=True)),
                ('im', models.CharField(blank=True, max_length=15, null=True)),
                ('ot', models.CharField(blank=True, max_length=27, null=True)),
                ('dr', models.CharField(blank=True, max_length=10, null=True)),
                ('w', models.CharField(blank=True, max_length=5, null=True)),
                ('smo', models.CharField(blank=True, max_length=7, null=True)),
                ('vpolis', models.CharField(blank=True, max_length=10, null=True)),
                ('spolis', models.CharField(blank=True, max_length=10, null=True)),
                ('npolis', models.CharField(blank=True, max_length=18, null=True)),
                ('dbeg', models.CharField(blank=True, max_length=10, null=True)),
                ('dstop', models.DateField(blank=True, null=True)),
                ('extnr', models.CharField(blank=True, max_length=9, null=True)),
                ('smo_ok', models.CharField(blank=True, max_length=5, null=True)),
                ('smo_ogrn', models.CharField(blank=True, max_length=15, null=True)),
                ('dend', models.CharField(blank=True, max_length=10, null=True)),
                ('novor', models.CharField(blank=True, max_length=9, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
