# Generated by Django 3.2.6 on 2022-02-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0014_updatepersdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatepersdata',
            name='smo_ogrn_r',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='updatepers',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='update_pers/%Y/%m/%d'),
        ),
    ]
