# Generated by Django 3.2.6 on 2022-02-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0015_auto_20220216_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='v014',
            name='kod',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
