# Generated by Django 3.2.6 on 2022-04-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0016_v014_kod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tar_vt',
            name='isf',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tar_vt',
            name='otm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tar_vt',
            name='v_tp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
