# Generated by Django 3.2.6 on 2022-04-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0017_auto_20220404_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='V036',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_code', models.CharField(blank=True, max_length=200, null=True)),
                ('parameter', models.IntegerField(blank=True, null=True)),
                ('datebeg', models.DateField(blank=True, null=True)),
                ('dateend', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
