# Generated by Django 3.2.6 on 2022-07-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0018_v036'),
    ]

    operations = [
        migrations.AddField(
            model_name='otde',
            name='number_beds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
