# Generated by Django 3.2.6 on 2023-02-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0019_otde_number_beds'),
    ]

    operations = [
        migrations.CreateModel(
            name='vbb_ds_prk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=255)),
                ('kod_r', models.CharField(max_length=255)),
                ('naim', models.CharField(max_length=255)),
                ('kod_u', models.CharField(max_length=255)),
                ('kod_ud', models.CharField(max_length=255)),
                ('kod_rpm', models.CharField(max_length=255)),
                ('kod_vtm', models.CharField(max_length=255)),
                ('n_kd', models.CharField(max_length=255)),
                ('n_kdd', models.CharField(max_length=255)),
                ('miac', models.CharField(max_length=255)),
            ],
        ),
    ]
