# Generated by Django 3.2.6 on 2023-03-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0020_vbb_ds_prk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tar_vt',
            name='mkb',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
