# Generated by Django 3.2.6 on 2022-01-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='qwe',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
