# Generated by Django 3.2.6 on 2022-01-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient_qwe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='qwe',
        ),
    ]
