# Generated by Django 3.2.6 on 2022-01-24 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0003_auto_20220124_0516'),
        ('hospital', '0005_auto_20220121_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Med_dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('number_ser', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='okb2.code_med_dev')),
            ],
        ),
    ]
