# Generated by Django 3.2.6 on 2022-01-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_med_dev'),
    ]

    operations = [
        migrations.AddField(
            model_name='sluchay',
            name='med_dev',
            field=models.ManyToManyField(blank=True, to='hospital.Med_dev'),
        ),
    ]
