# Generated by Django 3.2.6 on 2022-01-25 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hospital.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0008_temp_monitoring_res'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oper', models.FileField(upload_to='documents/hospital/%Y/%m/%d', validators=[hospital.validators.validate_file])),
                ('monitoring_res', models.FileField(upload_to='documents/hospital/%Y/%m/%d', validators=[hospital.validators.validate_file])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
