# Generated by Django 3.2.6 on 2022-01-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_load'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Load',
        ),
    ]
