# Generated by Django 3.2.6 on 2022-01-25 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_auto_20220125_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_monitoring_res_10',
            fields=[
                ('temp_monitoring_res_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hospital.temp_monitoring_res')),
            ],
            bases=('hospital.temp_monitoring_res',),
        ),
    ]
