# Generated by Django 3.2.6 on 2022-01-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_patient_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='novor',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
