# Generated by Django 3.2.6 on 2022-01-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_patient_novor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sluchay',
            name='usl_ok',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
