# Generated by Django 3.2.6 on 2022-01-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_sluchay_usl_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='sluchay',
            name='lpu_1',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='sluchay',
            name='vidpom',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
