# Generated by Django 3.2.6 on 2022-01-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_auto_20220126_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='sluchay',
            name='podr',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
