# Generated by Django 3.2.6 on 2022-01-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_sluchay_podr'),
    ]

    operations = [
        migrations.AddField(
            model_name='sluchay',
            name='det',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
