# Generated by Django 3.2.6 on 2022-01-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_sluchay_det'),
    ]

    operations = [
        migrations.AddField(
            model_name='sluchay',
            name='tal_d',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sluchay',
            name='tal_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sluchay',
            name='tal_p',
            field=models.DateField(blank=True, null=True),
        ),
    ]
