# Generated by Django 3.2.6 on 2022-01-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_sluchay_kd_z'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sluchay',
            name='kd_z',
        ),
        migrations.AddField(
            model_name='le_vr',
            name='kd_z',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
