# Generated by Django 3.2.6 on 2022-01-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_auto_20220126_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='sluchay',
            name='ds2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sluchay',
            name='ds2_n',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
