# Generated by Django 3.2.6 on 2022-01-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0029_sluchay_idsp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sluchay',
            name='crit',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sluchay',
            name='ed_col',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='sluchay',
            name='kol_usl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='sluchay',
            name='n_ksg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sluchay',
            name='vb_p',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
