# Generated by Django 3.2.6 on 2022-01-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0030_auto_20220127_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='sluchay',
            name='dn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sluchay',
            name='p_cel',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='sluchay',
            name='profil_k',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sluchay',
            name='reab',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
