# Generated by Django 3.2.6 on 2022-01-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0032_auto_20220128_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_monitoring_res',
            name='date_inj',
        ),
        migrations.AddField(
            model_name='temp_monitoring_res',
            name='cod_mark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temp_monitoring_res',
            name='codemeddev',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temp_monitoring_res',
            name='col_inj',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temp_monitoring_res',
            name='data_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temp_monitoring_res',
            name='data_inj',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temp_monitoring_res',
            name='date_med',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temp_monitoring_res',
            name='dose_ing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='temp_monitoring_res',
            name='ed_izm',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='temp_monitoring_res',
            name='method_inj',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='temp_monitoring_res',
            name='number_ser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
