# Generated by Django 3.2.6 on 2022-01-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0033_auto_20220131_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_monitoring_res',
            name='date_inj',
            field=models.DateField(blank=True, null=True),
        ),
    ]
