# Generated by Django 3.2.6 on 2022-01-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0035_rename_dose_ing_temp_monitoring_res_dose_inj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_monitoring_res',
            name='date_inj',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='temp_monitoring_res',
            name='koef_up',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='temp_monitoring_res',
            name='koef_z',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
    ]
