# Generated by Django 3.2.6 on 2022-02-02 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0007_group_kc_group_code_usl_kz'),
        ('hospital', '0036_auto_20220131_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sluchay',
            name='ksg_osn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ksg_osn', to='okb2.group_kc_group'),
        ),
        migrations.AlterField(
            model_name='sluchay',
            name='ksg_sop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ksg_sop', to='okb2.group_kc_group'),
        ),
    ]
