# Generated by Django 3.2.6 on 2022-02-10 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0037_auto_20220202_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='le_vr',
            name='aro_let',
        ),
    ]
