# Generated by Django 3.2.6 on 2022-03-23 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0040_alter_le_vr_aro_let'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sluchay',
            name='vds',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sl', to='hospital.vds'),
        ),
    ]
