# Generated by Django 3.2.6 on 2022-04-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0042_sluchay_dskz2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sluchay',
            name='err',
            field=models.BooleanField(default=False),
        ),
    ]
