# Generated by Django 3.2.6 on 2022-04-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0043_sluchay_err'),
    ]

    operations = [
        migrations.AddField(
            model_name='sluchay',
            name='err_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
