# Generated by Django 3.2.6 on 2022-05-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0044_sluchay_err_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sluchay',
            name='oslo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.oslo'),
        ),
    ]
