# Generated by Django 3.2.6 on 2022-06-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0048_form_7'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_7',
            name='err',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form_7',
            name='fakt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form_7',
            name='free_mest_all',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form_7',
            name='per_bl_iz_dr_otd',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form_7',
            name='per_bl_v_dr_otd',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form_7',
            name='post_bl_all',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form_7',
            name='sost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form_7',
            name='sost_all_yh',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form_7',
            name='sost_na_tek',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form_7',
            name='vps',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form_7',
            name='ymer',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
