# Generated by Django 3.2.6 on 2022-06-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0049_auto_20220607_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_7',
            name='dat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
