# Generated by Django 3.2.6 on 2022-06-08 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0050_form_7_dat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form_7',
        ),
    ]
