# Generated by Django 3.2.6 on 2022-06-08 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0018_v036'),
        ('hospital', '0051_delete_form_7'),
    ]

    operations = [
        migrations.CreateModel(
            name='otdl7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IM1', models.CharField(blank=True, max_length=100, null=True)),
                ('PR_OTD', models.CharField(blank=True, max_length=10, null=True)),
                ('FK', models.IntegerField(blank=True, default=0)),
                ('KODI', models.IntegerField(blank=True, default=0)),
                ('FK_MZ', models.IntegerField(blank=True, default=0)),
                ('FK_R', models.IntegerField(blank=True, default=0)),
                ('K_SR', models.IntegerField(blank=True, default=0)),
                ('K_D_R', models.IntegerField(blank=True, default=0)),
                ('N_KD', models.IntegerField(blank=True, default=0)),
                ('tipe', models.IntegerField(blank=True, default=0)),
                ('OTD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='okb2.otde')),
            ],
        ),
        migrations.CreateModel(
            name='umer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAT', models.DateField(blank=True, null=True)),
                ('FAM', models.CharField(blank=True, max_length=100, null=True)),
                ('UMA', models.IntegerField(blank=True, default=0)),
                ('UM1', models.IntegerField(blank=True, default=0)),
                ('UMS', models.IntegerField(blank=True, default=0)),
                ('UMAR', models.IntegerField(blank=True, default=0)),
                ('UM1G', models.IntegerField(blank=True, default=0)),
                ('OTD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.otdl7')),
                ('PROF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='okb2.v020')),
            ],
        ),
    ]
