# Generated by Django 3.2.6 on 2022-06-08 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0018_v036'),
        ('hospital', '0052_otdl7_umer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='umer',
            new_name='umer7',
        ),
    ]
