# Generated by Django 3.2.6 on 2022-06-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0053_rename_umer_umer7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otdl7',
            name='KODI',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
