# Generated by Django 3.2.6 on 2022-06-08 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0018_v036'),
        ('hospital', '0054_alter_otdl7_kodi'),
    ]

    operations = [
        migrations.CreateModel(
            name='form7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAT', models.DateField(blank=True, null=True)),
                ('PR_OTD', models.CharField(blank=True, max_length=10, null=True)),
                ('OTD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.otdl7')),
                ('PROF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='okb2.v020')),
            ],
        ),
    ]
