# Generated by Django 3.2.6 on 2022-06-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0055_form7'),
    ]

    operations = [
        migrations.AddField(
            model_name='form7',
            name='F_K',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='F_KR',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='MUT',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='MUT3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='NALKA',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='NALKR',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='NALNA',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='NALNK',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='NALNN',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='NALNR',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='PERAN',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='PERAN_1G',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='PERAN_E',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='PERI',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='PERIZ',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='PERR',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='PERR_1G',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='PERR_E',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='PERW',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='PERWAN',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='PERWANE',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='PERWAN_1G',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='PERWR',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='PERWRE',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='PERWR_1G',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='PERWW',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='POST',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='POST1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='POST14',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='POST15',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='POST60',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='POSTDS',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='POSTSG',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='SMEST',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='SWK',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='S_MEN',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='S_MUT',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='TIP',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='UM',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='UMA',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='UMA1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='UMAE',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='UMAR',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='UMAR1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='UMARE',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='UMAR_1G',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='UMA_1G',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='UMPO',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='UM_1G',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='UM_E',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='UM_S',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='WIP',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='WIPDR',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='WIPDS',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='WIPST',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='form7',
            name='WIP_SDP',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
