# Generated by Django 3.2.6 on 2022-06-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0056_auto_20220608_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oper',
            name='oslo',
            field=models.ManyToManyField(blank=True, related_name='koda', to='hospital.Oslo'),
        ),
    ]
