# Generated by Django 3.2.6 on 2022-06-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0057_alter_oper_oslo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oper',
            name='oslo',
            field=models.ManyToManyField(blank=True, related_name='oslo', to='hospital.Oslo'),
        ),
    ]
