# Generated by Django 3.2.6 on 2022-10-17 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0019_otde_number_beds'),
        ('hospital', '0059_sluchay_ksg_osn2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sluchay',
            name='dskz3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dskz3', to='okb2.ds'),
        ),
    ]
