# Generated by Django 3.2.6 on 2023-04-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0062_sluchay_oopkk2'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_p',
            name='take_care',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
